### ISSUE TITLE
isName function handle only name with 3 characters.

### ISSUE THREAD

**Issue by outsideris** [twitter/twitter-korean-text#24]
In [isName](https://github.com/twitter/twitter-korean-text/blob/korean-text-2.2/src/main/scala/com/twitter/penguin/korean/util/KoreanSubstantive.scala#L41-L48), it only accept name has 3 characters. 
But some Koreans has 2 characters name or 4 characters name such like "허균", "이황", "남궁옥분" and so on. 

And it is needed to add 2 characters family names(남궁, 황보, 제갈, 사공, 선우, 서문, 독고, 동방, 장곡, 어금, 강전, 소봉, 망절) to [family_names.txt](https://github.com/twitter/twitter-korean-text/blob/korean-text-2.2/src/main/resources/com/twitter/penguin/korean/util/substantives/family_names.txt) (see [Wikipedia](http://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%EC%9D%B8%EA%B5%AC%EC%88%9C_%EC%84%B1%EC%94%A8_%EB%AA%A9%EB%A1%9D))

**Comment by tglstory** [comment]
https://github.com/twitter/twitter-korean-text/pull/73 에서 address했습니다.

**Comment by penil** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kaylis@naver.com 님께 보내신 메일 <Re: [twitter-korean-text] isName function handle only name with 3 characters. (#24)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
