### ISSUE TITLE
Remove/separate compound nouns in the dictionary.

### ISSUE THREAD

**Issue by nlpenguin** [twitter/twitter-korean-text#4]
After numerous manual cleanups, [nouns from wikipedia titles](src/main/resources/com/twitter/penguin/korean/util/noun/wikipedia_title_nouns.txt) still includes many compound words (i.e. 동서울시외버스터미널). This should be divided into minimal nouns, for example, 동서울, 시외, 버스, 터미널, and 동서울시외버스터미널 should be removed.

**Comment by hsuvarna** [comment]
Hi,
Does this tokenizer/morphological analyzer work well for non-twitter kind of continuous text? Like in long documents?

-harish

**Comment by nlpenguin** [comment]
Yes, it does!
