### ISSUE TITLE
Add .NET wrapper

### ISSUE THREAD

**Issue by modamoda** [twitter/twitter-korean-text#54]
Is there any plan to implement .NET(especially C#) wrapper?

**Comment by nlpenguin** [comment]
No, not yet. But it's a great idea. I don't have expertise to tackle this, though. I would appreciate any help on this!

**Comment by modamoda** [comment]
![twitter korean analyzer](https://cloud.githubusercontent.com/assets/1969131/6932817/e0c54538-d859-11e4-9d72-8d769896983a.PNG)

With help from [IKVM](http://ikvm.net/) I could parse Korean sentence.(as seen on screenshot)
But I think there are several things to improvement.(unintuitive parameter names caused by `ikvmc`, C# style naming conventions...)

Could you recommend any good name for _namespace_ (equivalent to _package_ name in Java) for this wrapper library?

**Comment by nlpenguin** [comment]
Tweeted for help: https://twitter.com/NLPenguin/status/583421079076540416

**Comment by nlpenguin** [comment]
Comment from @roh0sun
@NLPenguin 저도 잘 모르지만요^^ jvm으로 구동되는 걸 .net api로 제공하려면 jni 레벨에서 작업해야 할텐데(어차피 jvm 프로세스 실행됨. 완전 돌아가기.) 그럴거면 차라리 웹서비스 api를 제공하는게 낫지 않을까 하는 생각했습니다
https://twitter.com/roh0sun/status/583486736719687681

**Comment by modamoda** [comment]
Thanks for twitting and forwarding! Here's my comments:
* I'm using `ikvmc`: Java bytecode - MSIL translator(`jar` => `dll`)
 * So JNI is not needed
* Building Scala/Java based API server could be another good workaround
 * But there might be negative effects like network traffic cost, performance.
 * Also .NET wrappers could have its own pros and cons. But developers can **choose** which workaround to use.

**Comment by yynewbies** [comment]
Hi modamoda, I have a question on conversion from jar file to dll file. I tried using run ikvmc using jar file generated from maven project in eclipse (source code from nlpenguin). During the process, it show warning messages like "warning IKVMC0105: Unable to compile class "com.twitter.penguin.korean.qa.BatchTokenizeTweets$$anonfun$4"
    (missing class "scala.runtime.AbstractFunction1")". May I know what is the reason? Many thanks

**Comment by nlpenguin** [comment]
@modamoda Can you please help @yynewbies on his question? Thanks!

**Comment by modamoda** [comment]
I hope this might help you: modamoda/TwitterKoreanProcessorCS#5
And FYI: I'm using IntelliJ and it works, but didn't tried on Eclipse

```
$ mono ~/Downloads/ikvm-7.2.4630.5/bin/ikvmc.exe -target:library korean-text.jar
IKVM.NET Compiler version 7.2.4630.5
Copyright (C) 2002-2012 Jeroen Frijters
http://www.ikvm.net/

note IKVMC0002: Output file is "korean-text.dll"
$ ls -al
...
-rwxr-xr-x  1 Joon  staff  9091072 Feb 12 15:46 korean-text.dll
```
