### ISSUE TITLE
Add Java version of KoreanPos and KoreanToken for better compatibility

### ISSUE THREAD

**Issue by nlpenguin** [twitter/twitter-korean-text#60]

**Comment by modamoda** [comment]
I hope [this code snippet](
https://github.com/modamoda/TwitterKoreanProcessorCS/blob/master/TwitterKoreanProcessorCS.cs#L150-L179) might help you. :smile: (and I also welcomes any advice on the code snippet)
Syntax of C# is very similar to Java

    public class KoreanToken
    {
        public string Text { get; set; }
        public KoreanPos Pos { get; set; }
        public bool Unknown { get; set; }

        public KoreanToken(com.twitter.penguin.korean.tokenizer.KoreanTokenizer.KoreanToken scalaToken)
        {
            this.Text = scalaToken.text().toString();
            this.Pos = (KoreanPos)scalaToken.pos().id();
            this.Unknown = scalaToken.unknown();
        }
    }

    public enum KoreanPos
    {
        // Word leved POS
        Noun, Verb, Adjective,
        Adverb, Determiner, Exclamation,
        Josa, Eomi, PreEomi, Conjunction,
        NounPrefix, VerbPrefix, Suffix, Unknown,

        // Chunk level POS
        Korean, Foreign, Number, KoreanParticle, Alpha,
        Punctuation, Hashtag, ScreenName,
        Email, URL, CashTag,

        // Functional POS
        Space, Others
    }

**Comment by nlpenguin** [comment]
Oh, thanks!!!

That was very fast! :)
