### ISSUE TITLE
Add Node.js wrapper

### ISSUE THREAD

**Issue by Ch0p** [twitter/twitter-korean-text#63]
I made a node.js wrapper in https://github.com/Ch0p/twtkrjs

What's your opinion about this?

**Comment by nlpenguin** [comment]
Thank you so much! This is awesome. I've added it to README.

**Comment by Ch0p** [comment]
thx :D 

 btw. Is there any plan to loading external dictionary file?

**Comment by nlpenguin** [comment]
what did you mean by loading external dictionary file? like integrating
with other dictionaries?  I can consider replacing the current dictionary
if the new one yields better results. :) After all the current dictionary
is what I manually created.

**Comment by Ch0p** [comment]
yes. integrating other dictionary 
if i set dictionary path, then program loads files i set path.

**Comment by nlpenguin** [comment]
Hmm I've never considered doing it. But it DOES sound like an interesting
idea. In the mean time, feel free to edit the dictionaries and see the diff
by "mvn test" and make a pull request.

**Comment by nlpenguin** [comment]
May I close this as you launched your wrapper very nicely? :)
