### ISSUE TITLE
Some characters are classified as a foreign, but I think these would be a punctuation.

### ISSUE THREAD

**Issue by widian** [twitter/twitter-korean-text#71]
These are "·" , "’" and "…". I think these would be a punctuation instead of foreign, because some koreans are using it as a Korean (I think it depends on their device).

**Comment by penil** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kaylis@naver.com 님께 보내신 메일 <[twitter-korean-text] Some characters are classified as a foreign, but I think these would be a punctuation. (#71)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by nlpenguin** [comment]
What you said totally makes sense. I will work on it this weekend.

**Comment by penil** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

kaylis@naver.com 님께 보내신 메일 <Re: [twitter-korean-text] Some characters are classified as a foreign, but I think these would be a punctuation. (#71)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by nlpenguin** [comment]
https://github.com/twitter/twitter-korean-text/pull/75/files 코드 리뷰 부탁드립니다.
