### ISSUE TITLE
slf4j-nop needs a non-default scope

### ISSUE THREAD

**Issue by slackhappy** [twitter/twitter-korean-text#77]
Not sure how this is being used, but it shouldn't be included in the library's default scope, because it will become present on the referencing project's classpath, where it will compete with other logging implementations.

Please move this dep to a non-default scope, such as `test`
http://www.slf4j.org/faq.html#maven2

**Comment by slackhappy** [comment]
Or provided, as it was before bba5e01045ff1b2a8b87905ff515c19062543f62

**Comment by tglstory** [comment]
We excluded the slf4j-nop on our side, no immediate deploy is required.
