### ISSUE TITLE
Detokenizer throws exception with certain inputs

### ISSUE THREAD

**Issue by laeubli** [twitter/twitter-korean-text#90]
I've come across a minor bug in the newly added detokenization routine, where some inputs result in a `java.lang.UnsupportedOperationException`. Example:
```scala
com.twitter.penguin.korean.TwitterKoreanProcessor.detokenize(List("이", "제품을", "사용하겠습니다"))
// throws java.lang.UnsupportedOperationException: empty.init
```
It seems like this could be easily fixed by initialising the list to be output differently. For now, I'm circumventing the problem by always prepending an empty string to the input:
```scala
com.twitter.penguin.korean.TwitterKoreanProcessor.detokenize(List("", "이", "제품을", "사용하겠습니다"))
// works
```
This is neither critical nor urgent, but it would be nice if this could be fixed in some of the future releases of this great library.

**Comment by nlpenguin** [comment]
Thanks for filing the issue. I've created a patch in #92.
